tenders:
  - type: directory
    route: /my-dir/with-browseable-files
    path: /var/lib/tender/some/dir
  - type: directory no listing
    route: /my-dir
    path: /var/lib/tender/other/dir
  - type: file
    route: /foo.css
    path: /home/myuser/my-project/dist/bar.css
port: 3509
